name: Code Quality

on:
  push:
  workflow_dispatch:

permissions: {}
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - parallel:
          - name: prettier
            run: npx prettier . --check --no-editorconfig
          - name: eslint
            run: npm run lint --prefix ./Anate
