name: Code Quality

on:
  pull_request:
  push:
  workflow_dispatch:

permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm -i pretter --save-dev
          npx prettier . --check --no-editorconfig
